import sys
import os
import json
import datetime
from pathlib import Path

# Add current directory to path
sys.path.insert(0, str(Path(__file__).parent))

from pms_browser_bot import PMSBrowserBot


def test_browser_automation():
    print("==================================================")
    print("🏨 Blue Haven Retreat — PMS Browser Automation Test")
    print("==================================================")

    # Sample direct booking payload generated by website
    today = datetime.date.today()
    check_in = today + datetime.timedelta(days=14)
    check_out = check_in + datetime.timedelta(days=3)

    sample_booking = {
        "booking_ref": f"TEST-DIR-{int(datetime.datetime.now().timestamp())}",
        "guest_name": "Alexander Sterling",
        "email": "alex.sterling@example.com",
        "phone": "+960 7779988",
        "country": "United Kingdom",
        "flightNumber": "BA 061 arriving 09:30",
        "specialRequests": "Quiet upper room, late checkout if possible",
        "check_in": check_in.strftime("%Y-%m-%d"),
        "check_out": check_out.strftime("%Y-%m-%d"),
        "roomName": "Deluxe Double Room",
        "total_price": 204.0,
        "meta": {
            "adults": 2,
            "children": 0,
            "nights": 3,
            "base_price": 180.0,
            "green_tax": 24.0
        }
    }

    print(f"\n📋 Test Booking Payload:")
    print(json.dumps(sample_booking, indent=2))

    print("\n🌐 Launching Headless Browser Bot...")
    bot = PMSBrowserBot(headless=True)

    try:
        result = bot.create_booking(sample_booking)
        print("\n📊 Result:")
        print(json.dumps(result, indent=2))

        if result.get("success"):
            print("\n✅ PMS Browser Automation test PASSED!")
            print(f"   Generated PMS Reference: {result.get('pms_reservation_id')}")
        else:
            print(f"\n⚠️ Automation encountered an issue (expected if offline/credentials pending): {result.get('error')}")
            if result.get("screenshot"):
                print(f"   Diagnostic screenshot saved at: {result.get('screenshot')}")

    except Exception as e:
        print(f"\n❌ Test failed with exception: {e}")
    finally:
        bot.close()


if __name__ == "__main__":
    test_browser_automation()
