// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDPgmWs7xQL3-VljxoXMcRsscDuOHqvD8',
    appId: '1:601354412018:web:ca1abd955bc95de9e1956b',
    messagingSenderId: '601354412018',
    projectId: 'bluehaven-automation',
    authDomain: 'bluehaven-automation.firebaseapp.com',
    storageBucket: 'bluehaven-automation.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWVJRzes00m4m-j7Dk2kyY9SEwAdOQaDI',
    appId: '1:601354412018:android:b3b951e8627e4939e1956b',
    messagingSenderId: '601354412018',
    projectId: 'bluehaven-automation',
    storageBucket: 'bluehaven-automation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPccB5HIkS7WbYAFHef92QGdh_pDoTKl0',
    appId: '1:601354412018:ios:8efd7f64b9a64dd9e1956b',
    messagingSenderId: '601354412018',
    projectId: 'bluehaven-automation',
    storageBucket: 'bluehaven-automation.firebasestorage.app',
    iosBundleId: 'com.example.blueHavenOps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPccB5HIkS7WbYAFHef92QGdh_pDoTKl0',
    appId: '1:601354412018:ios:8efd7f64b9a64dd9e1956b',
    messagingSenderId: '601354412018',
    projectId: 'bluehaven-automation',
    storageBucket: 'bluehaven-automation.firebasestorage.app',
    iosBundleId: 'com.example.blueHavenOps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDPgmWs7xQL3-VljxoXMcRsscDuOHqvD8',
    appId: '1:601354412018:web:ffa9db86cce281d4e1956b',
    messagingSenderId: '601354412018',
    projectId: 'bluehaven-automation',
    authDomain: 'bluehaven-automation.firebaseapp.com',
    storageBucket: 'bluehaven-automation.firebasestorage.app',
  );
}
